### ISSUE TITLE
emotions data in FDboost?

### ISSUE THREAD

**Issue by davidruegamer** [fdboost/FDboost#4]
davidruegamer/FDboost_Tutorial#21

**Comment by davidruegamer** [comment]
Added data set and documentation.

**Comment by sbrockhaus** [comment]
In my opinion, we should delete the variables `time_long` and `curveid`, as they only make sense for the response in long format which is not present in the data. What do you thing? 

In addition, `time_long` has other values thant `t`. `time_long` is 52, 53, 54, ... and `t` is 1, 2, 3, ...

**Comment by davidruegamer** [comment]
hmm... If I'm not mistaken I actually added those to the data set, because it was your wish to have a curve id and the time in long format in order to save some code lines in the paper, where we alternatively would have to create those variables. I'm indifferent :blush:

**Comment by sbrockhaus** [comment]
sorry, then it was a misunderstanding. I wanted to have `s` and `t` and for the regular response no more data precprcessing as it is now. 

For the response in long format, I think it is better when all variables are created together so that the reader can see how the work together. I already included that code in the paper draft.

**Comment by davidruegamer** [comment]
Ok. I will delete `time_long` and `curveid`, change the description and adjust the code in the paper.

**Comment by sbrockhaus** [comment]
Thank you very much and sorry for the mess... The code in the paper is already adjusted.

**Comment by davidruegamer** [comment]
Thanks :+1:
